

#run the viability classifier
run_viability <- function(input, values, session){
    if (is.null(values$markerMapping)){
        return (NULL)
    }
    
    #Read in the viability classifier
    classifier <- readRDS(system.file("extdata", "Viability_classifier.RDS", package="cytoclops"))
    housekeepers <- rownames(classifier$importance)
    
    #extract the markers that we use 
    mark <- sapply(housekeepers,function(x)input[[paste0("Housekeeper_", x)]])
    markers <- values$markerMapping[mark]
    
    #add a progress bar
    withProgress(message = 'Running viability classifier ... ',
                 detail = 'This may take a while...',
                 value = 0.0, {
                     
                     #next process one sample at a time
                     lapply(1:length(values$flowset), 
                            classify, 
                            input, 
                            values, 
                            session, 
                            markers, 
                            mark, 
                            housekeepers,
                            classifier)
                 })
    
    #update the panels and lists
    update_current_gate(session, input, values)
    update_children_table(session, input, values)
    replace_gating_list(input, values, session, selected = names(values$gatingPanels)[1])
}

#next process one sample at a time
classify <- function(idx, input, values, session, 
                     markers, mark, housekeepers,
                     classifier){
    
    #extract the right data 
    # + 1 to avoid median divisions by 0 and inf values generated by log2
    mat <- exprs(values$flowset[[idx]])[,markers] + 1 
    colnames(mat) <- housekeepers
    
    #transform the data (log2 + median centering)
    mat <- log2(sweep(mat ,2,colMedians(mat),'/'))
    
    #run the model, 
    pred <- predict(classifier, mat, type = "prob")
    
    #extract the indices
    indices <- (1:nrow(pred))[pred[, 2] > input$ViabilitySlider]
    
    #drop all the gatings that have been done before
    current_nam <- paste0('G',idx)
    values$currentID <- (1:length(values$gatingPanels))[names(values$gatingPanels) == current_nam]
    
    #remove all children of the current gate if there are any
    if (length(values$gatingPanels[[values$currentID]]@children) > 0){
        remove_child(input, values, session, values$currentID, paste0(current_nam,'_'))
    }
    
    #add a new gatingPanel with the viable cells
    add_new_child(input, 
                  values, 
                  session,
                  indices = indices,
                  name = 'Viable cells',
                  xmarker = mark[1],
                  ymarker = mark[3])
    
    #increment the progress bar
    incProgress(amount = 1 / length(values$flowset))
    
}